vich_uploader:
    db_driver: orm

    mappings:
        photos:
            namer: vich_uploader.namer_origname
            uri_prefix: /images/photos
            upload_destination: '%kernel.project_dir%/public/images/photos'
